name: aanthonycorp
favicon: null
layout_spectrum: 0.3396879092324525
typography_spectrum: 0.11345450486987829
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.15006117429584265
  lightness: 0.9854111846070737
  saturation: 0.20740806101821363
  rhythmicContrast: 0.048559440299868584
purpose: []
